version: "3.9"

services:
  backend:
    container_name: complaint-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/complaints_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      AI_SERVICE_BASE_URL: http://ai-service:8000
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
      - ai-service
    networks:
      - complaint-network

  ai-service:
    container_name: complaint-ai
    build:
      context: ./ai-microservices
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - complaint-network

  postgres:
    container_name: complaint-postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: complaints_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - complaint-network

  # redis:
  #   image: redis:7
  #   container_name: complaint-redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - complaint-network

volumes:
  postgres_data:

networks:
  complaint-network:
    driver: bridge
